orders_test/account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='account/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='account/logout.html'),
        name='logout'
    ),
]

orders_test/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.index, name='orders_list'),
    path('order_create/', views.order_create, name='order_create'),
    path(
        'order_detail/<int:order_id>/',
        views.order_detail,
        name='order_detail'
    ),
    path(
        'order_detail/<int:order_id>/docs/<str:path>',
        views.download,
        name='fdownload'
    ),
    path(
        'order_completed/<int:order_id>/',
        views.order_completed,
        name='order_completed'
    ),
    path(
        'order_rejected/<int:order_id>/',
        views.order_rejected,
        name='order_rejected'
    ),
    path('docs/<str:path>/', views.download, name='download'),
    path('orders_statistic/', views.orders_statistic, name='orders_statistic')
]

orders_test/orders_test/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('orders.urls', namespace='orders')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
]

orders_test/account/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
    )
    date_of_birth = models.DateField(
        verbose_name='Дата рождения',
    )
    is_customer = models.BooleanField(
        default=True,
        verbose_name='Заказчик',
    )
    is_manage = models.BooleanField(
        default=False,
        verbose_name='Исполнитель',
    )

    class Meta:
        ordering = ['user']

    def __str__(self):
        return self.user.username

orders_test/orders/models.py
from django.db import models

from account.models import User


class Order(models.Model):
    """Модель заказа."""

    class ChoicesStatus(models.TextChoices):
        NEW_ORD = ('new', 'Новый')
        COMPLETED_ORD = ('completed', 'Выполнен')
        REJECTED_ORD = ('rejected', 'Отклонен')

    customer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='orders',
        verbose_name='Заказчик',
    )
    text = models.TextField()
    file = models.FileField(
        upload_to='docs/',
        verbose_name='Документ',
    )
    status = models.CharField(
        max_length=15,
        choices=ChoicesStatus.choices,
        default=ChoicesStatus.NEW_ORD,
        verbose_name='Статус заказа'
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-id']

    def __str__(self):
        return self.text[:30]

orders_test/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from account.models import Profile, User


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class ProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        label='Дата рождения',
        widget=forms.DateInput(format='%d-%m-%Y', attrs={'type': 'date'}),
        required=False
    )

    class Meta:
        model = Profile
        fields = ('date_of_birth', 'is_manage', 'is_customer',)

orders_test/orders/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):
    """Форма создания заказа."""

    class Meta:
        model = Order
        fields = ['text', 'file']

orders_test/account/views.py
from django.shortcuts import render

from account.forms import ProfileForm, UserRegistrationForm


def register(request):
    template = 'account/register.html'
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            new_user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = new_user
            profile.save()

            return render(request, 'orders/index.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, template, context)

orders_test/orders/views.py
import os

from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from account.models import Profile, User
from orders.forms import OrderForm
from orders.models import Order
from orders_test import settings


@login_required
def index(request):
    """Список заказов."""
    template = 'orders/index.html'
    user = request.user
    if user.profile.is_manage:
        orders = Order.objects.all()
    else:
        orders = user.orders.all()

    context = {
        'orders': orders,
    }
    return render(request, template, context)


@login_required
def order_create(request):
    """Создание заказа."""
    template = 'orders/order_create.html'
    if not request.user.profile.is_customer:
        return redirect('orders:orders_list')

    if request.method == 'POST':
        form = OrderForm(request.POST, request.FILES)
        if form.is_valid():
            order = form.save(commit=False)
            order.customer = request.user
            order.save()
            return redirect('orders:orders_list')
    else:
        form = OrderForm()
    context = {'form': form}
    return render(request, template, context)


@login_required
def order_detail(request, order_id):
    """Просмотр заказа."""
    template = 'orders/order_detail.html'
    order = get_object_or_404(Order, pk=order_id)
    context = {'order': order}
    return render(request, template, context)


@login_required
def order_completed(request, order_id):
    """Выполнить заказ."""
    order = get_object_or_404(Order, pk=order_id)
    order.status = Order.ChoicesStatus.COMPLETED_ORD
    order.save()
    return redirect('orders:orders_list')


@login_required
def order_rejected(request, order_id):
    """Отклонить заказ."""
    order = get_object_or_404(Order, pk=order_id)
    order.status = Order.ChoicesStatus.REJECTED_ORD
    order.save()
    return redirect('orders:orders_list')


@login_required
def download(request, order_id=None, path=''):
    """Скачать документ приложенный к заказу."""
    file_path = os.path.join(settings.MEDIA_ROOT, 'docs/' + path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(
                fh.read(), content_type="application/vnd.ms-excel"
            )
            response['Content-Disposition'] = (
                    'inline; filename=' + os.path.basename(file_path)
            )
            return response
    raise Http404


@login_required
def orders_statistic(request):
    """Статистика по заказам."""
    print(request.user, request.user.profile.is_manage)
    if not request.user.profile.is_manage:
        return redirect('orders:orders_list')

    template = 'orders/statistic.html'
    orders_count = Order.objects.count()
    status_count = Order.objects.values('status').annotate(
        total=Count('status')
    ).order_by()

    context = {
        'orders_count': orders_count,
        'status_count': status_count
    }
    return render(request, template, context)

orders_test/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="utf-8">
    <title>
      {% block title%}
      {% endblock title%}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
        {% endblock content %}
      </div>
    </main>
  </body>
</html>

orders_test/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      {% if request.user.is_authenticated %}
        {% if request.user.profile.is_customer %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'orders:order_create' %}active{% endif %}" href="{% url 'orders:order_create' %}">Создать заказ</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'orders:orders_list' %}active{% endif %}" href="{% url 'orders:orders_list' %}">Список заказов</a>
        </li>
        {% if request.user.profile.is_manage %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'orders:orders_statistic' %}active{% endif %}" href="{% url 'orders:orders_statistic' %}">Статистика</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'account:logout' %}active{% endif %}" href="{% url 'account:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'account:login' %}active{% endif %}" href="{% url 'account:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'account:signup' %}active{% endif %}" href="{% url 'account:signup' %}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
    {% endwith %}
  </div>
</nav>

orders_test/templates/orders/index.html
{% extends 'base.html' %}
{% block title%}
  Список заказов
{% endblock title%}
{% block content %}
  <div class="container py-5">
    <h2>Список заказов</h2>
    {% if request.user.is_authenticated %}
      <table class="table-bordered">
        <tr>
          <th>Имя</th>
          <th>Дата рождения</th>
          <th>Заказ</th>
          <th>Документ</th>
          <th>Статус заказа</th>
        </tr>
    {% else %}
      <p>Для просмотра списка заказов, войдите в свою учетную запись</p>
    {% endif %}

        {% for order in orders %}
        <tr>
          <th>
            {{ order.customer.get_full_name }}
          </th>
            <th>
              {{ order.customer.profile.date_of_birth }}
            </th>
          <th>
            {{ order.text|truncatechars:30 }}
          </th>
          <th>
            <a href="{{ order.file }}">Документ</a>
          </th>
          <th>
            {{ order.status }}
          </th>
          <th>
            <a href="{% url 'orders:order_detail' order.pk %}">Посмотреть заказ</a>
          </th>
        </tr>
        {% endfor %}

      </table>
  </div>
{% endblock content %}

orders_test/templates/orders/order_create.html
{% extends 'base.html' %}
{% block title %}
Создание заказа:
{% endblock title %}


{% block content %}
  <h1>Создание заказа</h1>

  <form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Создать</button>
<!--    <p><input type="submit" value="Create"></p>-->
  </form>
{% endblock %}

orders_test/templates/orders/order_detail.html
{% extends 'base.html' %}
{% block title%}
  Заказ
{% endblock title%}

{% block content %}
  <div class="row">
    <article class="col-12 col-md-9">
      <p>Заказчик: {{ order.customer.get_full_name }}</p>
      <p>Дата рождения: {{ order.customer.profile.date_of_birth }}</p>
      <p>Текст: {{ order.text }}</p>
      <p> <a href="{{ order.file }}">Документ</a></p>
      {% if request.user.profile.is_manage %}
        <a class="btn btn-primary" href="{% url 'orders:order_rejected' order.id %}">Отклонить</a>
        <a class="btn btn-primary" href="{% url 'orders:order_completed' order.id %}">Выполнить</a>
      {% endif %}
    </article>
  </div>
{% endblock content %}

orders_test/templates/orders/statistic.html
{% extends 'base.html' %}
{% block title %}
  Статистика
{% endblock title%}

{% block content %}
  <div class="container py-5">
    <h2>Количество заказов в категориях:</h2>
    {% for c in status_count %}
      <p>{{ c.status }}: {{ c.total }}</p>
    {% endfor %}
    Всего: {{ orders_count }}
  </div>
{% endblock content %}